version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Previous Visual Studio 2019
platform: Any CPU
build:
  verbosity: minimal
configuration: Release
before_build:
  - ps: nuget restore Unchase.FluentPerformanceMeter.sln
build_script:
  - msbuild Unchase.FluentPerformanceMeter.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Unchase.FluentPerformanceMeter-v$(appveyor_build_version)
  auth_token:
    secure: 5YjB5tKbw0Z/mnSTKxo3WLD9TWuyGpGPhaNlSTA+cFA1oORUk46i6tPuyvekHaS9
  repository: unchase/Unchase.FluentPerformanceMeter
  artifact: /.*\.nupkg/
  force_update: true
  # on:
    #branch: master                # release from master branch only
    #appveyor_repo_tag: false       # deploy on tag push only
notifications:
- provider: Email
  to:
    - spiritkola@hotmail.com
  subject: 'Unchase.FluentPerformanceMeter - Build {{status}}'
  message: "Building complete, commitId = {{commitId}}"
  on_build_status_changed: true